services:
    crontab.listener.request:
        class: Crontab\EventListener\RequestListener
        arguments: [ @service_container ]
        tags:
           - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    crontab.cache.clearer:
        class: Crontab\Cache\ClearCache
        tags:
            - { name: kernel.cache_clearer }