services:
    cronbundle.listener.request:
        class: VM\Cron\EventListener\RequestListener
        arguments: [ @service_container ]
        tags:
           - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }

    cronbundle.cache.clearer:
        class: VM\Cron\Cache\ClearCache
        tags:
            - { name: kernel.cache_clearer }